### PR TITLE
support platform selection flag and configuration

### PR DESCRIPTION
**Pull request by cppforlife**
allows users to select images (from img indexes) matching only specific platform via global flag or explicit configuration in overrides

### CODE REVIEW

**Comment by voor** [comment]
Is there a global option to just have a kbld config that defaults every image to platformSelection?

**Comment by cppforlife** [comment]
@voor `--platform` command line flag would do it. did you want config option as well?

**Comment by voor** [comment]
We're trying to enable consistency without baking cli options into our scripts, but since we're on a single architecture this might be preemptive optimization

**Comment by cppforlife** [comment]
i see, im a little bit hesitant to add a config option right now without seeing some concrete usage first (of flags or individual per image platform selection). a bit fuzzy if folks may have images with windows and linux mixed together, etc.

**Pull request merged**
